const US_STATES: Record<string, string> = {
  'Alabama': 'alabama',
  'AL': 'alabama',
  'Alaska': 'alaska',
  'AK': 'alaska',
  'Arizona': 'arizona',
  'AZ': 'arizona',
  'Arkansas': 'arkansas',
  'AR': 'arkansas',
  'California': 'california',
  'CA': 'california',
  'Colorado': 'colorado',
  'CO': 'colorado',
  'Connecticut': 'connecticut',
  'CT': 'connecticut',
  'Delaware': 'delaware',
  'DE': 'delaware',
  'Florida': 'florida',
  'FL': 'florida',
  'Georgia': 'georgia',
  'GA': 'georgia',
  'Hawaii': 'hawaii',
  'HI': 'hawaii',
  'Idaho': 'idaho',
  'ID': 'idaho',
  'Illinois': 'illinois',
  'IL': 'illinois',
  'Indiana': 'indiana',
  'IN': 'indiana',
  'Iowa': 'iowa',
  'IA': 'iowa',
  'Kansas': 'kansas',
  'KS': 'kansas',
  'Kentucky': 'kentucky',
  'KY': 'kentucky',
  'Louisiana': 'louisiana',
  'LA': 'louisiana',
  'Maine': 'maine',
  'ME': 'maine',
  'Maryland': 'maryland',
  'MD': 'maryland',
  'Massachusetts': 'massachusetts',
  'MA': 'massachusetts',
  'Michigan': 'michigan',
  'MI': 'michigan',
  'Minnesota': 'minnesota',
  'MN': 'minnesota',
  'Mississippi': 'mississippi',
  'MS': 'mississippi',
  'Missouri': 'missouri',
  'MO': 'missouri',
  'Montana': 'montana',
  'MT': 'montana',
  'Nebraska': 'nebraska',
  'NE': 'nebraska',
  'Nevada': 'nevada',
  'NV': 'nevada',
  'New Hampshire': 'new-hampshire',
  'NH': 'new-hampshire',
  'New Jersey': 'new-jersey',
  'NJ': 'new-jersey',
  'New Mexico': 'new-mexico',
  'NM': 'new-mexico',
  'New York': 'new-york',
  'NY': 'new-york',
  'North Carolina': 'north-carolina',
  'NC': 'north-carolina',
  'North Dakota': 'north-dakota',
  'ND': 'north-dakota',
  'Ohio': 'ohio',
  'OH': 'ohio',
  'Oklahoma': 'oklahoma',
  'OK': 'oklahoma',
  'Oregon': 'oregon',
  'OR': 'oregon',
  'Pennsylvania': 'pennsylvania',
  'PA': 'pennsylvania',
  'Rhode Island': 'rhode-island',
  'RI': 'rhode-island',
  'South Carolina': 'south-carolina',
  'SC': 'south-carolina',
  'South Dakota': 'south-dakota',
  'SD': 'south-dakota',
  'Tennessee': 'tennessee',
  'TN': 'tennessee',
  'Texas': 'texas',
  'TX': 'texas',
  'Utah': 'utah',
  'UT': 'utah',
  'Vermont': 'vermont',
  'VT': 'vermont',
  'Virginia': 'virginia',
  'VA': 'virginia',
  'Washington': 'washington',
  'WA': 'washington',
  'West Virginia': 'west-virginia',
  'WV': 'west-virginia',
  'Wisconsin': 'wisconsin',
  'WI': 'wisconsin',
  'Wyoming': 'wyoming',
  'WY': 'wyoming',
  'Washington, D.C.': 'washington-dc',
  'DC': 'washington-dc',
  'D.C.': 'washington-dc',
  'District of Columbia': 'washington-dc',
};

const COUNTRIES: Record<string, string> = {
  'United States': 'united-states',
  'US': 'united-states',
  'USA': 'united-states',
  'France': 'france',
  'FR': 'france',
  'Italy': 'italy',
  'IT': 'italy',
  'Spain': 'spain',
  'ES': 'spain',
  'United Kingdom': 'united-kingdom',
  'UK': 'united-kingdom',
  'GB': 'united-kingdom',
  'Germany': 'germany',
  'DE': 'germany',
  'Japan': 'japan',
  'JP': 'japan',
  'Mexico': 'mexico',
  'MX': 'mexico',
  'Canada': 'canada',
  'CA': 'canada',
  'Australia': 'australia',
  'AU': 'australia',
  'Argentina': 'argentina',
  'AR': 'argentina',
  'Peru': 'peru',
  'PE': 'peru',
  'Brazil': 'brazil',
  'BR': 'brazil',
  'Thailand': 'thailand',
  'TH': 'thailand',
  'South Korea': 'south-korea',
  'KR': 'south-korea',
  'India': 'india',
  'IN': 'india',
  'Singapore': 'singapore',
  'SG': 'singapore',
  'Sweden': 'sweden',
  'SE': 'sweden',
  'Denmark': 'denmark',
  'DK': 'denmark',
  'Netherlands': 'netherlands',
  'NL': 'netherlands',
  'Belgium': 'belgium',
  'BE': 'belgium',
  'Switzerland': 'switzerland',
  'CH': 'switzerland',
  'Austria': 'austria',
  'AT': 'austria',
  'Portugal': 'portugal',
  'PT': 'portugal',
  'Greece': 'greece',
  'GR': 'greece',
  'Turkey': 'turkey',
  'TR': 'turkey',
  'Israel': 'israel',
  'IL': 'israel',
  'South Africa': 'south-africa',
  'ZA': 'south-africa',
  'Philippines': 'philippines',
  'PH': 'philippines',
  'Vietnam': 'vietnam',
  'VN': 'vietnam',
  'Indonesia': 'indonesia',
  'ID': 'indonesia',
  'China': 'china',
  'CN': 'china',
  'Taiwan': 'taiwan',
  'TW': 'taiwan',
  'Hong Kong': 'hong-kong',
  'HK': 'hong-kong',
  'Colombia': 'colombia',
  'CO': 'colombia',
  'Chile': 'chile',
  'CL': 'chile',
};

export function getStateSlug(state: string | null | undefined): string | null {
  if (!state) return null;
  return US_STATES[state] || null;
}

export function getCountrySlug(country: string | null | undefined): string | null {
  if (!country) return null;
  return COUNTRIES[country] || null;
}

export function isUSLocation(country: string | null | undefined): boolean {
  if (!country) return true;
  const normalized = country.toUpperCase();
  return normalized === 'US' || normalized === 'USA' || normalized === 'UNITED STATES';
}

export function getLocationLink(
  state: string | null | undefined,
  country: string | null | undefined
): string | null {
  if (isUSLocation(country)) {
    const stateSlug = getStateSlug(state);
    return stateSlug ? `/states/${stateSlug}` : null;
  }
  
  const countrySlug = getCountrySlug(country);
  return countrySlug ? `/countries/${countrySlug}` : null;
}

export function getLocationDisplay(
  city: string,
  state: string | null | undefined,
  country: string | null | undefined
): string {
  if (isUSLocation(country)) {
    return state ? `${city}, ${state}` : city;
  }
  return country ? `${city}, ${country}` : city;
}
